# Generated by Django 5.2.17 on 2026-08-12 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('BINANCE', 'Binance Pay'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('CREDIT_CARD', 'Tarjeta de crédito'), ('BANK_TRANSFER', 'Transferencia bancaria')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('credentials_encrypted', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
