# Generated by Django 5.2.17 on 2026-09-27 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBiometricCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.BigIntegerField(default=0)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credencial biométrica',
                'verbose_name_plural': 'credenciales biométricas',
                'db_table': 'user_biometric_credentials',
                'ordering': ('-created_at',),
            },
        ),
    ]
