# Generated by Django 5.2.17 on 2026-08-12 15:15

import apps.nfc.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFCSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayeeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('expires_at', models.DateTimeField(default=apps.nfc.models.default_expiry)),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.nfc.models.default_expiry)),
                ('state', models.CharField(choices=[('PENDING', 'Pendiente'), ('USED', 'Usado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
