# Generated by Django 5.2.17 on 2026-08-12 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nfc', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payeetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nfcsession',
            name='payee_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfc.payeetoken'),
        ),
        migrations.AddField(
            model_name='payertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nfcsession',
            name='payer_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nfc.payertoken'),
        ),
    ]
