# Generated by Django 5.2.17 on 2026-08-12 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('BINANCE', 'Binance Pay'), ('PAGO_MOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle'), ('CREDIT_CARD', 'Tarjeta de crédito'), ('BANK_TRANSFER', 'Transferencia bancaria')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('external_transaction_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(blank=True, max_length=64, null=True)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['app_id', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('app_id',), name='unique_fee_rule_per_app')],
            },
        ),
    ]
